apiVersion: v1
kind: Service
metadata:
  name: code-analyser-be
  labels:
    app: code-analyser-be
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 6060
    protocol: TCP
    name: http
  selector:
    app: code-analyser-be
