apiVersion: v1
kind: Service
metadata:
  name: github-client
  labels:
    app: github-client
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: github-client
